# Generated by Django 4.1.6 on 2023-07-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('category', models.CharField(max_length=600)),
                ('price', models.CharField(max_length=600)),
                ('image', models.ImageField(upload_to='images/')),
                ('first_name', models.CharField(max_length=600)),
                ('last_name', models.CharField(max_length=600)),
                ('phone_number', models.CharField(max_length=600)),
                ('address', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Buyurtmalar',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
