# Generated by Django 4.1.6 on 2023-07-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_telegrambot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ip',
            field=models.CharField(default='123', max_length=300),
            preserve_default=False,
        ),
    ]
